/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.List;

class AppTest {
    @Test void test() {
        App app = new App();
        List<Integer> nums1 = List.of(1, 3, 5, 7);
        List<Integer> nums2 = List.of(2, 4, 6, 8);
        List<Integer> nums3 = List.of(1, 2, 3, 4, 5, 6, 7, 8);
        assertEquals(app.zip(nums1, nums2), nums3);


        List<String> colors1 = List.of("Red", "Green", "Blue");
        List<String> colors2 = List.of("White", "Black", "Orange", "Pink", "Fuschia");
        List<String> color3 = List.of("Red", "White", "Green", "Black", "Blue", "Orange", "Pink", "Fuschia");
        assertEquals(app.zip(colors1, colors2), color3);
    }
}
